name: PR metadata annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: link-/PR-metadata-action@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  cordova-android:
    runs-on: ubuntu-latest
    name: Create and Build Android project
    steps:
      - name: Use oxr463/setup-cordova
        uses: oxr463/setup-cordova@0.0.3
        with:
          exec: |
            cordova create hello com.example.hello HelloWorld && \
            cd hello && \
            cordova platform add android && \
            cordova build --no-telemetry && \
            cp "$(find . -name '*.apk')" .        